import { Section, RecyclingEntry, MonthlyGoal } from '../types';

export const INITIAL_SECTIONS: Section[] = [
  {
    id: 'sec-1a',
    code: '1º A',
    name: '1º Año Sección A',
    grade: '1º Año',
    group: 'A',
    mascot: '🦅 Águilas Verdes',
    color: '#059669', // Emerald
    avatar: '🦅',
    slogan: '¡Volando alto por un planeta limpio!',
    advisor: 'Prof. Carlos Mendoza',
  },
  {
    id: 'sec-1b',
    code: '1º B',
    name: '1º Año Sección B',
    grade: '1º Año',
    group: 'B',
    mascot: '🐆 Jaguares Eco',
    color: '#d97706', // Amber
    avatar: '🐆',
    slogan: '¡Fuerza, velocidad y cero residuos!',
    advisor: 'Prof. Mariana Soto',
  },
  {
    id: 'sec-2a',
    code: '2º A',
    name: '2º Año Sección A',
    grade: '2º Año',
    group: 'A',
    mascot: '🌳 Guardianes del Roble',
    color: '#16a34a', // Green
    avatar: '🌳',
    slogan: '¡Raíces firmes, futuro verde!',
    advisor: 'Prof. Roberto Peña',
  },
  {
    id: 'sec-2b',
    code: '2º B',
    name: '2º Año Sección B',
    grade: '2º Año',
    group: 'B',
    mascot: '🐬 Delfines del Océano',
    color: '#0284c7', // Sky
    avatar: '🐬',
    slogan: '¡Mares limpios desde nuestras aulas!',
    advisor: 'Prof. Laura Gómez',
  },
  {
    id: 'sec-3a',
    code: '3º A',
    name: '3º Año Sección A',
    grade: '3º Año',
    group: 'A',
    mascot: '🐼 Pandas Sustentables',
    color: '#4f46e5', // Indigo
    avatar: '🐼',
    slogan: '¡Comiendo bambú y reciclando a full!',
    advisor: 'Prof. Gabriel Torres',
  },
  {
    id: 'sec-3b',
    code: '3º B',
    name: '3º Año Sección B',
    grade: '3º Año',
    group: 'B',
    mascot: '⚡ Titanes del Reciclaje',
    color: '#9333ea', // Purple
    avatar: '⚡',
    slogan: '¡La energía limpia nos mueve!',
    advisor: 'Prof. Elena Morales',
  },
  {
    id: 'sec-4a',
    code: '4º A',
    name: '4º Año Sección A',
    grade: '4º Año',
    group: 'A',
    mascot: '🦊 Zorros Circulares',
    color: '#ea580c', // Orange
    avatar: '🦊',
    slogan: '¡Astucia y compromiso ambiental!',
    advisor: 'Prof. Andrea Ruiz',
  },
  {
    id: 'sec-4b',
    code: '4º B',
    name: '4º Año Sección B',
    grade: '4º Año',
    group: 'B',
    mascot: '🐺 Lobos de la Tierra',
    color: '#0d9488', // Teal
    avatar: '🐺',
    slogan: '¡En manada cuidamos el planeta!',
    advisor: 'Prof. Fernando Silva',
  },
];

export const INITIAL_MONTHLY_GOAL: MonthlyGoal = {
  monthName: 'Octubre 2026',
  targetKilos: 1200,
  year: 2026,
  monthIndex: 9,
  schoolName: 'Instituto San Francisco de Asís',
};

// Seed realistic entries so the app opens with vibrant ranking, progress bar and stats
export const INITIAL_ENTRIES: RecyclingEntry[] = [
  {
    id: 'ent-1',
    sectionId: 'sec-3a',
    materialId: 'aluminio',
    kilos: 32.5,
    points: 975,
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 3, // 3 days ago
    formattedDate: '28 Sep 2026, 09:15',
    registeredBy: 'Valentina R. (3ºA)',
    notes: 'Campaña especial de latas recolectadas en la cafetería escolar.',
  },
  {
    id: 'ent-2',
    sectionId: 'sec-1a',
    materialId: 'plastico',
    kilos: 48.0,
    points: 720,
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 2.5,
    formattedDate: '28 Sep 2026, 14:30',
    registeredBy: 'Prof. Carlos Mendoza',
    notes: 'Botellas PET aplastadas y limpias entregadas en costales.',
  },
  {
    id: 'ent-3',
    sectionId: 'sec-2b',
    materialId: 'papel',
    kilos: 65.0,
    points: 650,
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 2,
    formattedDate: '29 Sep 2026, 11:00',
    registeredBy: 'Mateo L. (2ºB)',
    notes: 'Exámenes viejos y cuadernos en desuso de biblioteca.',
  },
  {
    id: 'ent-4',
    sectionId: 'sec-1b',
    materialId: 'vidrio',
    kilos: 52.0,
    points: 416,
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 1.8,
    formattedDate: '29 Sep 2026, 15:45',
    registeredBy: 'Prof. Mariana Soto',
    notes: 'Frascos de vidrio limpios sin tapas para centro de acopio.',
  },
  {
    id: 'ent-5',
    sectionId: 'sec-3a',
    materialId: 'plastico',
    kilos: 38.0,
    points: 570,
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 1.2,
    formattedDate: '30 Sep 2026, 10:20',
    registeredBy: 'Lucas D. (3ºA)',
    notes: 'Tapas plásticas y botellas de agua del patio central.',
  },
  {
    id: 'ent-6',
    sectionId: 'sec-3b',
    materialId: 'tetrapak',
    kilos: 28.5,
    points: 342,
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 1.1,
    formattedDate: '30 Sep 2026, 12:00',
    registeredBy: 'Camila P. (3ºB)',
    notes: 'Envases de jugo tetra pak abiertos y enjuagados.',
  },
  {
    id: 'ent-7',
    sectionId: 'sec-1a',
    materialId: 'papel',
    kilos: 74.0,
    points: 740,
    timestamp: Date.now() - 1000 * 60 * 60 * 20,
    formattedDate: '30 Sep 2026, 16:10',
    registeredBy: 'Prof. Carlos Mendoza',
    notes: 'Cajas de cartón del archivo administrativo recicladas.',
  },
  {
    id: 'ent-8',
    sectionId: 'sec-4a',
    materialId: 'aluminio',
    kilos: 18.0,
    points: 540,
    timestamp: Date.now() - 1000 * 60 * 60 * 16,
    formattedDate: '01 Oct 2026, 08:30',
    registeredBy: 'Joaquín S. (4ºA)',
    notes: 'Latas recolectadas durante el festival deportivo.',
  },
  {
    id: 'ent-9',
    sectionId: 'sec-2a',
    materialId: 'raee',
    kilos: 8.5,
    points: 425,
    timestamp: Date.now() - 1000 * 60 * 60 * 8,
    formattedDate: '01 Oct 2026, 10:00',
    registeredBy: 'Prof. Roberto Peña',
    notes: 'Campaña especial de pilas gastadas y cables en desuso.',
  },
  {
    id: 'ent-10',
    sectionId: 'sec-4b',
    materialId: 'plastico',
    kilos: 34.0,
    points: 510,
    timestamp: Date.now() - 1000 * 60 * 60 * 4,
    formattedDate: '01 Oct 2026, 11:45',
    registeredBy: 'Sofía M. (4ºB)',
    notes: 'Plásticos recolectados en el aula verde.',
  },
  {
    id: 'ent-11',
    sectionId: 'sec-3a',
    materialId: 'papel',
    kilos: 45.0,
    points: 450,
    timestamp: Date.now() - 1000 * 60 * 60 * 2,
    formattedDate: '01 Oct 2026, 12:30',
    registeredBy: 'Valentina R. (3ºA)',
    notes: 'Periódicos y folletos de las aulas de 3º año.',
  },
  {
    id: 'ent-12',
    sectionId: 'sec-2b',
    materialId: 'aluminio',
    kilos: 15.5,
    points: 465,
    timestamp: Date.now() - 1000 * 60 * 40,
    formattedDate: '01 Oct 2026, 13:10',
    registeredBy: 'Prof. Laura Gómez',
    notes: 'Latas de bebidas del quiosco saludable.',
  },
];
